name: Sync CBFS Files

on:
  workflow_run:
    workflows: ["Sync sources.sh from MrChromebox"]
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create directories
      run: mkdir -p cbfs temp

    - name: Download and compare bootorder.usb
      id: sync
      run: |
        set -e
        url="https://www.mrchromebox.tech/files/firmware/cbfs/bootorder.usb"
        dest="cbfs/bootorder.usb"
        temp="temp/bootorder.usb"

        curl -sL "$url" -o "$temp"

        if [ -f "$dest" ]; then
          if cmp -s "$dest" "$temp"; then
            echo "No change for $dest"
            rm "$temp"
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi

        echo "Updated or new file: $dest"
        mv "$temp" "$dest"
        echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.sync.outputs.changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add cbfs/bootorder.usb
        git commit -m "Update bootorder.usb from MrChromebox"
        git push
