name: Sync sources.sh from MrChromebox

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create temporary directory
      run: mkdir -p temp

    - name: Download and compare sources.sh
      id: sync
      run: |
        set -e
        url="https://raw.githubusercontent.com/MrChromebox/scripts/main/sources.sh"
        dest="sources.sh"
        temp="temp/sources.sh"

        curl -sL "$url" -o "$temp"

        if [ -f "$dest" ]; then
          if cmp -s "$dest" "$temp"; then
            echo "No change for $dest"
            rm "$temp"
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        fi

        echo "Updated or new file: $dest"
        mv "$temp" "$dest"
        echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.sync.outputs.changed == 'true'
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add sources.sh
        git commit -m "Update sources.sh from MrChromebox"
        git push
